(()=>{"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],C=$("#gameCanvas"),c=C.getContext("2d"),W=C.width,H=C.height,TAU=Math.PI*2,KEY="poopHomeRunLegend.v2";
const CONDITIONS={healthy:{name:"건강",color:"#55c86a",weights:[52,5,31,9,2.5,.5]},normal:{name:"보통",color:"#ffd83d",weights:[70,16,9,4,.8,.2]},tired:{name:"피곤",color:"#a98fc9",weights:[61,26,9,3,.8,.2]},upset:{name:"배탈",color:"#63d5ef",weights:[28,61,8,2.5,.4,.1]},peak:{name:"초절정",color:"#ff72c5",weights:[25,2,35,24,11,3]}};
const POOPS=[{id:"normal",name:"일반똥",desc:"가장 기본적인 똥",mult:1,target:1,color:"#754126",glow:"#0000"},{id:"watery",name:"물똥",desc:"빠르고 조준 범위 50% 감소",mult:1,target:.5,color:"#9a6b2f",glow:"#e9c35c"},{id:"hard",name:"단단한 똥",desc:"거리 보너스 +20%",mult:1.2,target:1,color:"#4b281b",glow:"#0000"},{id:"gold",name:"황금똥",desc:"희귀 · 거리 3배",mult:3,target:1,color:"#ffd52f",glow:"#fff48b"},{id:"rainbow",name:"무지개똥",desc:"초희귀 · 거리 5배",mult:5,target:1,color:"#ff72c5",glow:"#6df8ff"},{id:"nuclear",name:"전설의 핵똥",desc:"최고 등급 · 거리 10배",mult:10,target:1,color:"#6df04c",glow:"#dfff44"}];
const toolSheet=new Image(),gameScene=new Image();toolSheet.src="UI/tool.png";gameScene.src="UI/gameplay-screen.png";
const TOOL_SPRITES={shovel:[86,154,254,174],bat:[405,154,254,174],hammer:[724,154,254,174],golf:[1043,154,254,174],cannon:[86,422,254,174],tank:[405,422,254,174],railgun:[724,422,254,174]};
const TOOLS=[{id:"shovel",name:"삽",desc:"기본 장비",mult:1,price:0,icon:"♠",sprite:TOOL_SPRITES.shovel},{id:"bat",name:"야구방망이",desc:"거리 +20%",mult:1.2,price:250,icon:"▰",sprite:TOOL_SPRITES.bat},{id:"hammer",name:"망치",desc:"크리티컬 확률 증가",mult:1.1,crit:.12,price:700,icon:"⚒",sprite:TOOL_SPRITES.hammer},{id:"golf",name:"골프채",desc:"정확도 판정 범위 증가",mult:1.15,accuracy:.025,price:1300,icon:"⌟",sprite:TOOL_SPRITES.golf},{id:"cannon",name:"대포",desc:"거리 +100%",mult:2,price:3500,icon:"●",sprite:TOOL_SPRITES.cannon},{id:"tank",name:"전차포",desc:"거리 +300%",mult:4,price:9000,icon:"▣",sprite:TOOL_SPRITES.tank},{id:"railgun",name:"우주 레일건",desc:"거리 +1000%",mult:11,price:30000,icon:"⌁",sprite:TOOL_SPRITES.railgun}];
const REGIONS=[{name:"시골 마을",range:"STAGE 1 - 20",start:1,color:"#6fcf58",icon:"⌂",boss:"철벽 엉덩이 아저씨"},{name:"도시",range:"STAGE 21 - 40",start:21,color:"#6eaad2",icon:"▥",boss:"철벽 엉덩이 아저씨"},{name:"공장지대",range:"STAGE 41 - 60",start:41,color:"#a88d74",icon:"♨",boss:"황금 변기왕"},{name:"해외",range:"STAGE 61 - 80",start:61,color:"#ef9c62",icon:"♜",boss:"황금 변기왕"},{name:"우주",range:"STAGE 81 - 100",start:81,color:"#7250bd",icon:"✦",boss:"우주 배변 신"}];
const ACH=[{id:"m100",name:"동네 홈런왕",desc:"비거리 100m 달성",icon:"100",test:s=>s.best>=100},{id:"m500",name:"구름을 뚫고",desc:"비거리 500m 달성",icon:"500",test:s=>s.best>=500},{id:"km1",name:"킬로미터의 벽",desc:"비거리 1km 달성",icon:"1K",test:s=>s.best>=1e3},{id:"km10",name:"대륙 횡단",desc:"비거리 10km 달성",icon:"10K",test:s=>s.best>=1e4},{id:"gold",name:"황금의 손맛",desc:"황금똥 적중",icon:"G",test:s=>!!s.stats.goldHit},{id:"perfect100",name:"완벽주의자",desc:"Perfect 100회",icon:"P",test:s=>s.stats.perfect>=100},{id:"space",name:"우주 진출",desc:"스토리 81 스테이지 도달",icon:"★",test:s=>s.stage>=81}];
const DEF={coins:0,best:0,stage:1,equipped:"shovel",owned:["shovel"],discoveredPoops:[],records:[],achievements:{},battle:{date:"",used:0},stats:{plays:0,perfect:0,goldHit:false}};
let S=load(),screen="homeScreen",mode="story",state="idle",condition=CONDITIONS.normal,poop=POOPS[0],tool=TOOLS[0],arena=REGIONS[0],prepMode="story",prepOriginalCondition=CONDITIONS.normal,selectedBoosts=new Set(),powerBoost=1,targetRadius=205,targetDir=-1,targetCycles=0,power=.03,powerDir=1,aimGrade="",powerGrade=1,distance=0,shown=0,elapsed=0,flightTime=0,introTime=0,resultTime=0,shake=0,particles=[],flies=[],last=0,audio,toolCanvases={};
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return{...structuredClone(DEF),...x,battle:{...DEF.battle,...x.battle},stats:{...DEF.stats,...x.stats}}}catch{return structuredClone(DEF)}}
const persist=()=>localStorage.setItem(KEY,JSON.stringify(S)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),fmt=v=>v>=1e6?(v/1e6).toFixed(2)+" Mm":v>=1e3?(v/1e3).toFixed(2)+" km":Math.round(v)+" m",today=()=>new Date().toISOString().slice(0,10),toolBy=id=>TOOLS.find(x=>x.id===id)||TOOLS[0],region=(stage=S.stage)=>REGIONS[Math.min(4,Math.floor((stage-1)/20))];
function weighted(items,weights){let r=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<items.length;i++){r-=weights[i];if(r<=0)return items[i]}return items[0]}
function resetBattle(){if(S.battle.date!==today())S.battle={date:today(),used:0}}
function sync(){resetBattle();$("#coinCount").textContent=S.coins.toLocaleString("ko-KR");$("#homeBest").textContent=fmt(S.best);$("#stageProgress").textContent=`STAGE ${S.stage} / 100`;$("#collectionProgress").textContent=`${S.discoveredPoops.length+S.owned.length} / ${POOPS.length+TOOLS.length}`;$("#achievementProgress").textContent=`${Object.keys(S.achievements).length} / ${ACH.length}`;$("#battleTickets").textContent=`오늘 ${Math.max(0,3-S.battle.used)}회 무료`}
function show(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));screen=id;document.body.dataset.screen=id;$("#backButton").classList.toggle("hidden",id==="homeScreen");if(id==="storyScreen")renderRegions();if(id==="shopScreen")renderShop();if(id==="collectionScreen")renderCollection("poops");if(id==="achievementScreen")renderAchievements();if(id==="rankingScreen")renderRanking();sync()}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1800)}
function sound(type){audio||=new(window.AudioContext||window.webkitAudioContext);audio.resume();const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime;o.connect(g).connect(audio.destination);o.type=type==="miss"?"square":type==="hit"?"sawtooth":"sine";o.frequency.setValueAtTime(type==="miss"?120:type==="hit"?220:620,t);o.frequency.exponentialRampToValueAtTime(type==="miss"?45:type==="hit"?70:980,t+.3);g.gain.setValueAtTime(.13,t);g.gain.exponentialRampToValueAtTime(.001,t+.38);o.start();o.stop(t+.4)}
function renderRegions(){$("#regionList").innerHTML=REGIONS.map(r=>{const unlocked=S.stage>=r.start,current=region().name===r.name;return `<article class="region-card"><div class="icon" style="background:${r.color}">${unlocked?r.icon:"×"}</div><div><b>${r.name}${current?" · 진행 중":""}</b><small>${r.range} · 보스: ${r.boss}</small></div><button data-play-stage="${r.start}" ${unlocked?"":"disabled"}>${unlocked?"도전":"잠김"}</button></article>`}).join("")}
function toolSprite(t,w=96,h=76){const sp=t.sprite;if(!sp)return `<div class="icon">${t.icon}</div>`;const scale=Math.max(w/sp[2],h/sp[3]),iw=1378*scale,ih=768*scale,tx=-sp[0]*scale+(w-sp[2]*scale)/2,ty=-sp[1]*scale+(h-sp[3]*scale)/2;return `<div class="tool-sprite" style="width:${w}px;height:${h}px"><img src="UI/tool.png" alt="" style="width:${iw}px;height:${ih}px;transform:translate(${tx}px,${ty}px)"></div>`}
function renderShop(){$("#shopList").innerHTML=TOOLS.map(t=>{const owned=S.owned.includes(t.id),equipped=S.equipped===t.id;return `<article class="item-card tool-card ${equipped?"equipped":""}">${toolSprite(t,104,82)}<div class="tool-copy"><b>${t.name}</b><small>${t.desc}</small><em>${owned?"보유 중":t.price.toLocaleString("ko-KR")+" 코인"}</em></div><button data-tool="${t.id}" ${equipped?"disabled":""}>${equipped?"장착 중":owned?"장착":t.price.toLocaleString("ko-KR")+" 코인"}</button></article>`}).join("")}
function renderCollection(tab){$$(`[data-tab]`).forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));const list=tab==="poops"?POOPS:TOOLS;$("#collectionList").innerHTML=list.map(x=>{const found=tab==="poops"?S.discoveredPoops.includes(x.id):S.owned.includes(x.id),visual=tab==="poops"?`<div class="icon" style="${found?`background:${x.color};box-shadow:inset 0 0 14px ${x.glow}`:""}">${found?"●":"?"}</div>`:found?toolSprite(x,76,62):`<div class="icon">?</div>`;return `<article class="collection-card ${found?"":"locked"}">${visual}<b>${found?x.name:"미발견"}</b><small>${found?x.desc:"게임에서 발견하세요"}</small></article>`}).join("")}
function refreshAchievements(){ACH.forEach(a=>{if(!S.achievements[a.id]&&a.test(S)){S.achievements[a.id]=true;toast(`업적 달성: ${a.name}`)}})}
function renderAchievements(){refreshAchievements();$("#achievementList").innerHTML=ACH.map(a=>{const done=S.achievements[a.id];return `<article class="achievement-card ${done?"done":""}"><div class="icon">${a.icon}</div><div><b>${a.name}</b><small>${a.desc}</small></div><span class="check">${done?"✓":"·"}</span></article>`}).join("");persist()}
function renderRanking(){const rows=[...S.records].sort((a,b)=>b.distance-a.distance).slice(0,10),top=rows.slice(0,3);$("#rankingPodium").innerHTML=top.length?top.map((r,i)=>`<div class="podium-item"><b>${i+1}위</b><small>${fmt(r.distance)}</small></div>`).join(""):"<p>첫 기록에 도전하세요!</p>";$("#rankingList").innerHTML=rows.map((r,i)=>`<article class="rank-row"><b>${i+1}</b><div><b>${r.mode==="battle"?"대전":`STAGE ${r.stage}`}</b><small>${r.date}</small></div><strong>${fmt(r.distance)}</strong></article>`).join("")}
function battle(){resetBattle();if(S.battle.used>=3)return toast("오늘의 무료 대전 3회를 모두 사용했습니다.");openPrep("battle")}
function conditionKey(value){return Object.keys(CONDITIONS).find(key=>CONDITIONS[key]===value)||"normal"}
function conditionInfo(value){return{healthy:["건강","기운이 넘치고 표정도 여유롭습니다.","😄"],normal:["보통","무난하지만 약간 긴장한 상태입니다.","😐"],tired:["피곤","눈이 풀리고 힘이 부족합니다.","😪"],upset:["배탈","식은땀과 복통이 심합니다.","😖"],peak:["초절정","모든 감각이 폭발 직전입니다!","🤩"]}[conditionKey(value)]}
function renderPrep(){const current=selectedBoosts.has("medicine")?CONDITIONS.healthy:prepOriginalCondition,info=conditionInfo(current),cost=(selectedBoosts.has("medicine")?80:0)+(selectedBoosts.has("steroid")?150:0);$("#prepCondition").textContent=info[0];$("#prepCondition").style.color=current.color;$("#prepConditionDesc").textContent=selectedBoosts.has("medicine")?"회복약 효과로 건강을 되찾았습니다!":info[1];$("#prepFace").dataset.condition=conditionKey(current);$("#prepFace").setAttribute("aria-label",`${info[0]} 컨디션 표정`);$("#prepCost").textContent=`${cost} 코인`;$$(`[data-boost]`).forEach(button=>button.classList.toggle("selected",selectedBoosts.has(button.dataset.boost)));const medicine=$("[data-boost=medicine]");medicine.disabled=!["tired","upset"].includes(conditionKey(prepOriginalCondition));$("#arenaGrid").innerHTML=REGIONS.map((item,index)=>`<button data-arena="${index}" class="${arena===item?"selected":""}"><span>${item.icon}</span>${item.name}</button>`).join("")}
function openPrep(selectedMode){prepMode=selectedMode;prepOriginalCondition=weighted(Object.values(CONDITIONS),[25,38,17,14,6]);condition=prepOriginalCondition;arena=selectedMode==="battle"?REGIONS[0]:region();selectedBoosts=new Set();powerBoost=1;$("#prepMode").textContent=selectedMode==="battle"?"BATTLE PREP":"STORY PREP";$("#arenaSection").style.display=selectedMode==="battle"?"block":"none";renderPrep();$("#prepModal").classList.add("show")}
function confirmPrep(){const cost=(selectedBoosts.has("medicine")?80:0)+(selectedBoosts.has("steroid")?150:0);if(S.coins<cost)return toast("선택한 아이템을 구매할 코인이 부족합니다.");if(prepMode==="battle"){resetBattle();if(S.battle.used>=3)return toast("오늘의 무료 대전을 모두 사용했습니다.");S.battle.used++}S.coins-=cost;if(selectedBoosts.has("medicine"))condition=CONDITIONS.healthy;powerBoost=selectedBoosts.has("steroid")?1.5:1;persist();sync();$("#prepModal").classList.remove("show");startGame(prepMode)}
function introLine(){return{healthy:"오늘 컨디션이 좋아 보인다!",normal:"배가 아픈 것 같다...",tired:"힘이 조금 부족한데...",upset:"심상치 않은 신호가 온다!",peak:"엄청난 것이 나올 것 같은데?!"}[Object.keys(CONDITIONS).find(k=>CONDITIONS[k]===condition)]}
function isBossStage(stage=S.stage){return mode==="story"&&stage%20===0}
function updateBossHud(progress=0){const active=isBossStage(),hud=$("#bossHud");hud.classList.toggle("show",active);if(!active)return;$("#bossName").textContent=region(S.stage).boss;$("#bossHp").style.width=`${(1-clamp(progress,0,1))*100}%`}
function startGame(selected="story"){mode=selected;state="intro";elapsed=introTime=resultTime=distance=shown=0;particles=[];flies=[];poop=weighted(POOPS,condition.weights);tool=toolBy(S.equipped);targetRadius=205;targetDir=-1;targetCycles=0;power=.03;powerDir=1;aimGrade="";powerGrade=1;$("#modeLabel").textContent=mode==="battle"?"BATTLE · DAILY":`STORY · STAGE ${S.stage}`;$("#locationLabel").textContent=isBossStage()?`${arena.name} · BOSS`:arena.name;$("#conditionLabel").textContent=condition.name;$("#conditionLabel").style.color=condition.color;$("#equippedLabel").textContent=tool.name;$("#distanceLabel").textContent="0 m";$("#powerPanel").classList.remove("show");$("#gameHint").textContent="잠시 후 배출이 시작됩니다";$("#gameHint").style.display="";$("#statusMessage").textContent=isBossStage()?`${region(S.stage).boss} 등장!`:introLine();$("#resultModal").classList.remove("show");updateBossHud();show("gameScreen")}
function beginAim(){state="aim";elapsed=0;$("#statusMessage").textContent=`${poop.name} 출현!`;$("#gameHint").textContent="원이 Perfect 원과 겹칠 때 터치!";sound("coin")}
function judgeText(text,cls){const e=$("#judgement");e.textContent=text;e.className=`judgement ${cls}`;void e.offsetWidth;e.classList.add("show")}
function judgeAim(){if(state!=="aim")return;const error=Math.abs(targetRadius-54)/151,bonus=tool.accuracy||0;aimGrade=error<=.03+bonus?"Perfect":error<=.08+bonus?"Great":error<=.15+bonus?"Good":error<=.25+bonus?"Bad":"Miss";judgeText(aimGrade.toUpperCase(),aimGrade.toLowerCase());if(aimGrade==="Miss")return fail();state="power";power=.02;powerDir=1;$("#powerPanel").classList.add("show");$("#gameHint").style.display="none";sound("coin")}
function hitPower(){if(state!=="power")return;powerGrade=clamp(Math.ceil((1-Math.abs(power-.5)*2)*10),1,10);const superCrit=Math.abs(power-.5)<=.045;if(superCrit){powerGrade=10;judgeText("SUPER CRITICAL!","super")}else judgeText(`${powerGrade} POWER`,powerGrade>=8?"perfect":"good");const aim={Perfect:1,Great:.82,Good:.62,Bad:.35}[aimGrade],critical=Math.random()<.03+(tool.crit||0);distance=Math.round(230*aim*(.28+powerGrade*.092)*poop.mult*tool.mult*powerBoost*(1+(S.stage-1)*.008)*rand(.92,1.08)*(superCrit?1.35:1)*(critical?2:1));if(critical&&!superCrit)judgeText("CRITICAL ×2!","super");state="hit";elapsed=0;shake=aimGrade==="Perfect"?22:12;$("#powerPanel").classList.remove("show");$("#statusMessage").textContent=aimGrade==="Perfect"?"완벽한 타격!":"날아간다!";burst(470,595,aimGrade==="Perfect"?70:35,poop.color);sound("hit")}
function fail(){state="miss";elapsed=0;shake=28;distance=0;$("#powerPanel").classList.remove("show");$("#gameHint").style.display="none";$("#statusMessage").textContent="으악! 얼굴에 정통으로!";flies=Array.from({length:10},(_,i)=>({angle:i*.63,speed:rand(1.5,3.5)}));burst(305,530,90,"#754126");sound("miss")}
const stageGoal=s=>70+s*7.5;
function complete(){if(state==="result")return;state="result";const playedStage=S.stage,bossClear=isBossStage(playedStage)&&distance>=stageGoal(playedStage);S.stats.plays++;if(aimGrade==="Perfect")S.stats.perfect++;if(poop.id==="gold"&&distance>0)S.stats.goldHit=true;if(!S.discoveredPoops.includes(poop.id)){S.discoveredPoops.push(poop.id);toast(`도감 등록: ${poop.name}`)}const record=distance>S.best;S.best=Math.max(S.best,distance);const earned=distance?Math.max(3,Math.floor(Math.sqrt(distance)*1.8)):0;S.coins+=earned;S.records.push({distance,mode,stage:playedStage,date:new Date().toLocaleDateString("ko-KR")});S.records=S.records.sort((a,b)=>b.distance-a.distance).slice(0,30);if(mode==="story"&&distance>=stageGoal(playedStage))S.stage=Math.min(100,playedStage+1);refreshAchievements();persist();sync();$("#resultKicker").textContent=record?"NEW RECORD":bossClear?"BOSS CLEAR":mode==="battle"?"BATTLE RESULT":"STAGE RESULT";$("#resultGrade").textContent=distance?aimGrade.toUpperCase()+"!":"MISS!";$("#resultDistance").textContent=fmt(distance);$("#resultDetail").textContent=`${powerGrade} POWER · ${poop.name} · ${tool.name}${powerBoost>1?" · 증강제":""}`;$("#resultCoins").textContent=`+${earned}`;$("#resultPoop").style.background=poop.color;$("#resultPoop").style.boxShadow=`0 0 22px ${poop.glow}`;$("#resultModal").classList.add("show")}
function update(dt){elapsed+=dt;shake*=.9;particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=560*dt;p.life-=dt});particles=particles.filter(p=>p.life>0);if(state==="intro"){introTime+=dt;if(introTime>2.4)beginAim()}else if(state==="aim"){const speed=(95+(poop.id==="watery"?38:0))/poop.target;targetRadius+=targetDir*speed*dt;if(targetRadius<=34){targetRadius=34;targetDir=1}if(targetRadius>=205){targetRadius=205;targetDir=-1;if(++targetCycles>=2)fail()}}else if(state==="power"){power+=powerDir*dt*1.25;if(power>=1||power<=0){power=clamp(power,0,1);powerDir*=-1}$("#powerNeedle").style.left=`calc(${power*100}% - 4px)`;$("#powerLevel").textContent=clamp(Math.ceil((1-Math.abs(power-.5)*2)*10),1,10)}else if(state==="hit"&&elapsed>.65){state="flight";flightTime=0;$("#statusMessage").textContent=poop.id==="nuclear"?"전설의 핵똥 폭주!":"비거리 측정 중!"}else if(state==="flight"){flightTime+=dt;const duration=clamp(2.8+Math.log10(distance+1)*.7,3,6),p=clamp(flightTime/duration,0,1);shown=distance*(1-(1-p)**2.5);$("#distanceLabel").textContent=fmt(shown);if(isBossStage())updateBossHud(shown/stageGoal(S.stage));if(p>=1){resultTime+=dt;if(resultTime>.45)complete()}}else if(state==="miss"&&elapsed>1.8)complete()}
function burst(x,y,n,color){for(let i=0;i<n;i++){const a=rand(0,TAU),s=rand(90,520);particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,r:rand(3,12),color,life:rand(.45,1.2)})}}
function rr(x,y,w,h,r,fill,stroke="#2b1838",lw=5){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=lw;c.stroke()}}
function cloud(x,y,s){c.save();c.translate(((x%(W+220))+W+220)%(W+220)-100,y);c.scale(s,s);c.fillStyle="#ffffffc9";[[0,20,44],[48,0,62],[104,22,46]].forEach(q=>{c.beginPath();c.arc(...q,0,TAU);c.fill()});c.restore()}
function drawSceneReference(progress=0){const iw=gameScene.naturalWidth,ih=gameScene.naturalHeight,scale=Math.max(W/iw,H/ih),sw=W/scale,sh=H/scale,sx=(iw-sw)/2,sy=Math.max(0,(ih-sh)/2);c.drawImage(gameScene,sx,sy,sw,sh,0,0,W,H);c.fillStyle="rgba(255,238,174,.12)";c.fillRect(0,0,W,H);if(state==="flight"){c.fillStyle="rgba(44,32,77,.16)";c.fillRect(0,0,W,H);c.fillStyle="rgba(255,255,255,.2)";for(let i=0;i<5;i++){const x=((i*190-progress*.12)%900)-120;c.fillRect(x,760+i%2*34,130,5)}}}
function background(progress=0){if(gameScene.complete&&gameScene.naturalWidth)return drawSceneReference(progress);const r=arena;if(state==="flight"&&(S.stage>=81||shown>8000)){c.fillStyle="#120c31";c.fillRect(0,0,W,H);for(let i=0;i<70;i++){c.fillStyle=i%7?"#fff":"#fff45b";c.fillRect((i*137-progress*.2)%W,(i*83)%820,i%3+2,i%3+2)}c.fillStyle="#5c4b86";c.fillRect(0,880,W,240);return}const sky=c.createLinearGradient(0,0,0,850);sky.addColorStop(0,r.name==="우주"?"#392e75":"#68cbed");sky.addColorStop(1,"#d9f6f1");c.fillStyle=sky;c.fillRect(0,0,W,H);c.fillStyle="#fff29a";c.beginPath();c.arc(610,110,55,0,TAU);c.fill();cloud(120-progress*.08,150,1);cloud(570-progress*.14,290,.72);c.fillStyle=r.color;c.fillRect(0,760,W,360);c.fillStyle="#489a42";c.beginPath();c.moveTo(0,800);for(let x=0;x<=W;x+=90)c.lineTo(x,735+Math.sin(x*.025)*25);c.lineTo(W,H);c.lineTo(0,H);c.fill();scenery(progress,r)}
function scenery(p,r){if(r.name==="시골 마을")for(let i=-1;i<5;i++){const x=((i*250-p*.45)%1250)-100;c.fillStyle=i%2?"#ffe0a1":"#ffb86b";c.fillRect(x,650,150,125);c.fillStyle="#a74e39";c.beginPath();c.moveTo(x-18,650);c.lineTo(x+75,570);c.lineTo(x+168,650);c.fill()}else if(r.name==="도시")for(let i=-1;i<7;i++){const x=((i*140-p*.6)%1100)-100,h=170+(i*47%180);c.fillStyle=i%2?"#65798b":"#7f6f89";c.fillRect(x,760-h,105,h)}else if(r.name==="공장지대"){c.fillStyle="#6d625f";for(let i=-1;i<5;i++){const x=((i*230-p*.55)%1300)-100;c.fillRect(x,590,170,190);c.fillRect(x+105,460,38,130)}}else if(r.name==="해외"){const x=500-(p*.5%1000);c.strokeStyle="#485758";c.lineWidth=18;c.beginPath();c.moveTo(x,780);c.lineTo(x+80,430);c.lineTo(x+160,780);c.stroke()}}
function extractedTool(t){if(toolCanvases[t.id])return toolCanvases[t.id];if(!(toolSheet.complete&&toolSheet.naturalWidth&&t.sprite))return null;const [sx,sy,sw,sh]=t.sprite,off=document.createElement("canvas"),oc=off.getContext("2d",{willReadFrequently:true});off.width=sw;off.height=sh;oc.drawImage(toolSheet,sx,sy,sw,sh,0,0,sw,sh);const img=oc.getImageData(0,0,sw,sh),d=img.data,samples=[[0,0],[sw-1,0],[0,sh-1],[sw-1,sh-1]].map(([x,y])=>{const i=(y*sw+x)*4;return[d[i],d[i+1],d[i+2]]});for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],max=Math.max(r,g,b),min=Math.min(r,g,b),bright=max>222&&max-min<55,corner=samples.some(([cr,cg,cb])=>(r-cr)**2+(g-cg)**2+(b-cb)**2<4200);if(bright||corner)d[i+3]=0}oc.putImageData(img,0,0);return toolCanvases[t.id]=off}
function drawToolSprite(){const source=extractedTool(tool);if(!source)return false;const dw=250,dh=dw*source.height/source.width;c.save();c.translate(230,35);c.rotate(state==="hit"?-1.7:-.55);c.drawImage(source,52,-dh/2,dw,dh);c.restore();return true}
function drawTool(){if(drawToolSprite())return;c.save();c.translate(230,35);c.rotate(state==="hit"?-1.7:-.55);c.strokeStyle="#744729";c.lineWidth=17;c.beginPath();c.moveTo(0,0);c.lineTo(240,0);c.stroke();const fill=tool.id==="railgun"?"#79f2ff":tool.id==="bat"?"#e6b16c":"#bac2c7";if(tool.id==="hammer")rr(185,-45,92,90,14,fill);else if(["cannon","tank","railgun"].includes(tool.id))rr(160,-32,145,64,20,fill);else if(tool.id==="bat")rr(160,-19,130,38,18,fill);else{c.fillStyle=fill;c.strokeStyle="#2b1838";c.lineWidth=7;c.beginPath();c.moveTo(195,-43);c.quadraticCurveTo(285,-53,293,0);c.quadraticCurveTo(280,54,195,43);c.closePath();c.fill();c.stroke()}c.restore()}
function drawReferencePlayer(){if(!(gameScene.complete&&gameScene.naturalWidth))return false;const sx=300,sy=265,sw=370,sh=500,bob=Math.sin(elapsed*5)*8+(state==="hit"?-18:0),lean=state==="hit"?-.18:state==="power"?.06:0,scale=1.02;c.save();c.translate(155,530+bob);c.rotate(lean);c.drawImage(gameScene,sx,sy,sw,sh,-130*scale,-210*scale,330*scale,445*scale);if(state==="intro"){c.fillStyle="rgba(255,216,61,.18)";c.beginPath();c.arc(46,18,120+Math.sin(introTime*8)*10,0,TAU);c.fill()}if(powerBoost>1){c.strokeStyle="#fff45f";c.lineWidth=8;c.beginPath();c.arc(75,38,116,0,TAU);c.stroke()}drawTool();c.restore();return true}
function character(){if(drawReferencePlayer())return;const key=conditionKey(condition),strain=state==="intro"?clamp(introTime/2.4,0,1):state==="miss"?1:.8;c.save();c.translate(155,650);c.lineCap="round";c.strokeStyle="#2b1838";c.lineWidth=17;c.beginPath();c.moveTo(85,105);c.lineTo(45,225);c.moveTo(145,105);c.lineTo(175,225);c.stroke();rr(25,-15,145,135,50,"#ff6d3b");c.fillStyle="#ffc78f";c.strokeStyle="#2b1838";c.lineWidth=6;c.beginPath();c.arc(-25,-85,76,0,TAU);c.fill();c.stroke();c.fillStyle="#503023";c.beginPath();c.arc(-30,-112,65,Math.PI,TAU);c.fill();c.stroke();c.fillStyle="#ffc78f";c.beginPath();c.arc(163,42,52,0,TAU);c.fill();c.stroke();c.beginPath();c.arc(126,42,52,0,TAU);c.fill();c.stroke();c.fillStyle="#8b4b37";c.beginPath();c.arc(190,49,8,0,TAU);c.fill();c.strokeStyle="#2b1838";c.lineWidth=7;if(key==="healthy"){c.beginPath();c.arc(-50,-88,6,0,TAU);c.arc(-5,-88,6,0,TAU);c.fillStyle="#2b1838";c.fill();c.beginPath();c.arc(-27,-62,21,0,Math.PI);c.stroke()}else if(key==="peak"){c.beginPath();c.moveTo(-60,-98);c.lineTo(-43,-89);c.moveTo(7,-98);c.lineTo(-10,-89);c.stroke();c.beginPath();c.ellipse(-27,-58,19,13,0,0,TAU);c.stroke()}else if(key==="tired"){c.beginPath();c.moveTo(-59,-87);c.lineTo(-42,-84);c.moveTo(-12,-84);c.lineTo(5,-87);c.stroke();c.beginPath();c.moveTo(-40,-58);c.lineTo(-15,-58);c.stroke()}else{c.beginPath();c.moveTo(-60,-95);c.lineTo(-42,-84+strain*5);c.moveTo(6,-95);c.lineTo(-12,-84+strain*5);c.stroke();c.beginPath();c.ellipse(-27,-57,14+strain*8,8+strain*9,0,0,TAU);c.stroke()}if(key==="upset"||key==="tired")for(let i=0;i<(key==="upset"?3:1);i++){c.fillStyle="#61d8ec";c.beginPath();c.ellipse(28-i*13,-80+i*9,7,13,-.25,0,TAU);c.fill()}if(powerBoost>1){c.strokeStyle="#fff45f";c.lineWidth=8;c.beginPath();c.arc(73,35,105,0,TAU);c.stroke()}if(state==="miss"){c.fillStyle="#754126";c.beginPath();c.arc(-23,-84,39,0,TAU);c.fill()}drawTool();c.restore()}
function drawPoop(x,y,s,rot=0){c.save();c.translate(x,y);c.rotate(rot);c.scale(s,s);c.shadowColor=poop.glow;c.shadowBlur=poop.id==="normal"?0:25;c.fillStyle=poop.color;c.strokeStyle="#2b1838";c.lineWidth=7;c.beginPath();c.moveTo(-66,58);c.bezierCurveTo(-98,21,-65,-6,-40,-9);c.bezierCurveTo(-62,-40,-23,-57,-4,-47);c.bezierCurveTo(-16,-82,22,-93,31,-57);c.bezierCurveTo(67,-62,78,-25,53,-7);c.bezierCurveTo(102,5,91,49,67,59);c.closePath();c.fill();c.stroke();c.shadowBlur=0;c.fillStyle="#2b1838";c.beginPath();c.arc(-27,8,8,0,TAU);c.arc(28,8,8,0,TAU);c.fill();c.lineWidth=4;c.beginPath();c.arc(0,28,18,0,Math.PI);c.stroke();if(poop.id==="rainbow"){c.strokeStyle="#6df8ff";c.lineWidth=8;c.beginPath();c.arc(0,0,82,0,TAU);c.stroke()}c.restore()}
function target(){c.save();c.translate(510,508);c.setLineDash([14,9]);c.strokeStyle="#fff45f";c.lineWidth=10;c.beginPath();c.arc(0,0,58,0,TAU);c.stroke();c.setLineDash([]);c.strokeStyle=targetRadius<=66?"#fff45f":"#fff";c.lineWidth=9;c.shadowColor=targetRadius<=66?"#fff45f":"#6df8ff";c.shadowBlur=22;c.beginPath();c.arc(0,0,targetRadius,0,TAU);c.stroke();c.shadowBlur=0;c.fillStyle="#ffffff";c.font="900 18px sans-serif";c.textAlign="center";c.strokeStyle="#2b1838";c.lineWidth=5;c.strokeText("PERFECT",0,6);c.fillText("PERFECT",0,6);c.restore()}
function flight(){const duration=clamp(2.8+Math.log10(distance+1)*.7,3,6),p=clamp(flightTime/duration,0,1),x=92+p*565,y=720-Math.sin(p*Math.PI)*540;c.strokeStyle=poop.id==="rainbow"?"#ff72c5aa":"#ffffffaa";c.lineWidth=24;c.beginPath();c.moveTo(x-185,y+48);c.lineTo(x,y);c.stroke();drawPoop(x,y,.68+Math.sin(p*Math.PI)*.38,flightTime*5)}
function drawGameHud(){c.save();c.fillStyle="rgba(43,24,56,.72)";rr(24,24,215,58,18,"rgba(43,24,56,.72)","#fff4ce",3);c.fillStyle="#fff";c.font="900 17px sans-serif";c.fillText(mode==="battle"?"BATTLE":`STAGE ${S.stage}`,44,59);rr(480,24,216,58,18,"rgba(43,24,56,.72)","#fff4ce",3);c.textAlign="right";c.fillStyle="#ffd83d";c.font="900 24px sans-serif";c.fillText(fmt(shown||distance),674,61);c.textAlign="left";if(isBossStage()){rr(34,94,650,34,14,"rgba(43,24,56,.65)","#fff4ce",2);c.fillStyle="#ef4d3f";c.fillRect(48,106,Math.max(0,610*(1-(shown/stageGoal(S.stage)))),10);c.fillStyle="#fff";c.font="900 11px sans-serif";c.fillText(region(S.stage).boss,56,119)}c.restore()}
function draw(){c.save();if(shake>.2)c.translate(rand(-shake,shake),rand(-shake,shake));background(state==="flight"?shown:0);drawGameHud();if(["intro","aim","power","hit","miss"].includes(state))character();if(state==="aim"){drawPoop(510,508,.72,elapsed*1.5);target()}else if(state==="power")drawPoop(510,508,.78);else if(state==="hit")drawPoop(510+elapsed*410,508-elapsed*285,.78,elapsed*8);else if(state==="flight")flight();else if(state==="intro"){const r=clamp((introTime-1.1)/1.1,0,1);if(r>0)drawPoop(345+r*165,684-r*176,.18+r*.54,r*3)}if(state==="miss")flies.forEach(f=>{f.angle+=.04*f.speed;const x=175+Math.cos(f.angle)*125,y=570+Math.sin(f.angle*1.7)*90;c.fillStyle="#15111a";c.beginPath();c.ellipse(x,y,8,4,f.angle,0,TAU);c.fill()});particles.forEach(p=>{c.globalAlpha=clamp(p.life,0,1);c.fillStyle=p.color;c.beginPath();c.arc(p.x,p.y,p.r,0,TAU);c.fill()});c.globalAlpha=1;c.restore()}
function frame(t){const dt=Math.min((t-last)/1e3||0,.033);last=t;if(screen==="gameScreen")update(dt);draw();requestAnimationFrame(frame)}
$("#tapZone").addEventListener("pointerdown",()=>state==="aim"?judgeAim():state==="power"?hitPower():0);$("#retryButton").onclick=()=>{$("#resultModal").classList.remove("show");mode==="battle"?battle():openPrep("story")};$("#homeButton").onclick=()=>{$("#resultModal").classList.remove("show");state="idle";show("homeScreen")};$("#backButton").onclick=()=>{state="idle";$("#resultModal").classList.remove("show");show("homeScreen")};
document.addEventListener("click",e=>{const sb=e.target.closest("[data-screen]");if(sb)show(sb.dataset.screen);if(e.target.closest('[data-action="battle"]'))battle();if(e.target.closest("[data-play-stage]"))openPrep("story");const tb=e.target.closest("[data-tool]");if(tb){const t=toolBy(tb.dataset.tool);if(S.owned.includes(t.id)){S.equipped=t.id;toast(`${t.name} 장착 완료`)}else if(S.coins>=t.price){S.coins-=t.price;S.owned.push(t.id);S.equipped=t.id;toast(`${t.name} 구매 완료`)}else return toast("코인이 부족합니다.");persist();sync();renderShop()}const tab=e.target.closest("[data-tab]");if(tab)renderCollection(tab.dataset.tab);const boost=e.target.closest("[data-boost]");if(boost&&!boost.disabled){selectedBoosts.has(boost.dataset.boost)?selectedBoosts.delete(boost.dataset.boost):selectedBoosts.add(boost.dataset.boost);renderPrep()}const arenaButton=e.target.closest("[data-arena]");if(arenaButton){arena=REGIONS[Number(arenaButton.dataset.arena)];renderPrep()}});$("#prepStartButton").onclick=confirmPrep;$("#prepCancelButton").onclick=()=>$("#prepModal").classList.remove("show");document.addEventListener("keydown",e=>{if(!["Space","Enter"].includes(e.code)||screen!=="gameScreen")return;e.preventDefault();state==="aim"?judgeAim():state==="power"?hitPower():0});sync();show("homeScreen");requestAnimationFrame(frame);if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
})();
